### ISSUE TITLE
Error: unexpected symbol in "git status"

### ISSUE THREAD

**Issue by MHenderson** [gaborcsardi/gitty#3]
```
✔  master*
❯ git status
Error: unexpected symbol in "git status"

✖  master*
❯ git
❯ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
```

I'm getting the `unexpected symbol` error whenever I call a git command but when I call `git` by itself afterwards (as above) it runs the previous command just fine.

```
❯ sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: BunsenLabs GNU/Linux 8.4 (Hydrogen)

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] prompt_1.0.0 gitty_1.0.0 

loaded via a namespace (and not attached):
[1] clisymbols_1.0.0 whisker_0.3-2    crayon_1.3.2
```

```
15:56:42 matthew@bunsen ~ git --version
git version 2.1.4
```

**Comment by gaborcsardi** [comment]
I cannot reproduce this. What is the environment? Terminal? Also, do you set `options(error)` to something? `gitty` needs to use that, too. 

Do you have problems if you start R with `R --vanilla`?

**Comment by MHenderson** [comment]
I'm using zsh in the Terminator application. I get the same problem with `R --vanilla`. My `options(error)` set to:

```
(function () 
{
    update_prompt(expr = NA, value = NA, ok = FALSE, visible = NA)
    orig <- prompt_env$error
    if (!is.null(orig) && is.function(orig)) 
        orig()
})()
```

I think the issue is caused by my trying to load the `gitty` package at startup. I have the following in `~/.Rprofile`

```
options(RDocs.override = TRUE)

.First <- function(){
  library(gitty)
  library(prompt)
  set_prompt(prompt_fancy)
  cat("\nWelcome at", date(), "\n")
}
```
I get the problem above if I start R with this `.Rprofile` but I don't get the same problem if I use `--no-init-file` and do `library(gitty)` after R has started.

Inicdentally, the above problem also goes away even if I use the `.Rprofile` above but also do `library(gitty)` after starting R.

So it seems like I'm probably abusing `.Rprofile` and shouldn't load packages there like I have been doing.

**Comment by MHenderson** [comment]
Updating my `.Rprofile` fixes it:

```
options(RDocs.override = TRUE)

.First <- function(){
  options(defaultPackages=c(getOption("defaultPackages"),
       "gitty"))
  prompt::set_prompt(prompt::prompt_fancy)
  cat("\nWelcome at", date(), "\n")
}

```

**Comment by gaborcsardi** [comment]
The problem is that the `prompt` package also overwrites `options("error")`.

It would be nice to have a way to define multiple error handlers.....

On Tue, Jan 17, 2017 at 9:37 AM, Matthew Henderson <notifications@github.com
