### ISSUE TITLE
What is the RStudio IDE missing for support?

### ISSUE THREAD

**Issue by jimhester** [gaborcsardi/gitty#5]
Now that the IDE has some support for ANSI escapes what is missing for gitty support?

**Comment by gaborcsardi** [comment]
1. It is not possible to go back up and remove the error message, but this is only a glitch. 

2. Somehow, I cannot define an error callback:
```r
> options(error = recover)
> getOption("error")
NULL
```

Not sure why this is.

**Comment by gaborcsardi** [comment]
Looks like 2. is a bug that was fixed already.

**Comment by gaborcsardi** [comment]
OK, it kind of works now. However, 
1. there are no colors, because the git auto-detection does not work. We can try to force colors in git, maybe.
2. we cannot go up on the console with the cursor, so the error message is not deleted.

**Comment by jimhester** [comment]
For 1. looks like you can pass `--colors` to git to unconditionally use colors (https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration)

**Comment by gaborcsardi** [comment]
Yeah, I tried, actually, but still does not really work:
<img width="522" alt="Screen Shot 2019-05-17 at 3 17 04 PM" src="https://user-images.githubusercontent.com/660288/57935661-39c56a00-78ba-11e9-9742-75dbbdf0a211.png">

It does not look completely hopeless, but considering that there are also issues with tab-completion, I'll postpone the gitty on RStudio project now....
